name: Publish release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish release
        env:
          BINTRAY_USER: ${{ secrets.BintrayUser }}
          BINTRAY_PAS: ${{ secrets.BintrayPass }}
        run: sbt publish
